version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    env_file:
      - db_config.env
    ports:
      - "3306:3306"

  ngrok:
    image: ngrok/ngrok:alpine
    restart: always
    ports:
      - "4551:4551"
    links:
      - api

  api:
    build: api/
    ports:
      - "8080:8080"
    restart: always

  monitor:
    build: monitor/
    restart: always
